# Generated by Django 5.0.3 on 2024-04-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounted_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
