# Generated by Django 5.0.3 on 2024-04-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
    ]
